[package]
name = "fret-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
plotters = "0.3.7"
rand = "0.8.5"
rand_distr = "0.4.3"
terminal_size = "0.1"
eframe = "0.24"
rfd = "0.12"